---
- name: 'Converge'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Converge | apply r_pufky.deb.apt'
      ansible.builtin.include_role:
        name: 'r_pufky.deb.apt'

    - name: 'Converge | apply r_pufky.deb.apt (remove yarn)'
      ansible.builtin.include_role:
        name: 'r_pufky.deb.apt'
      vars:
        apt_pins:
          - name: 'yarn_remove'
            state: 'absent'
