---
###############################################################################
# Pin
###############################################################################
# Ensure APT pinning and removal work correctly. Removal of non-existing pin
# should not lead to role failure.
#
# Tests:
# * APT pin is created correctly.
# * Removing a non-existent APT pin does not cause role to fail.

dependency:
  name: 'galaxy'
driver:
  name: 'podman'
provisioner:
  name: 'ansible'
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
    ssh_connection:
      pipelining: false
  inventory:
    group_vars:
      all:
        apt_pins:
          - name: 'nodejs_keep'
            package: 'nodejs'
            pin: 'origin deb.nodesource.com'
            pin_priority: 1001
            state: 'present'
          - name: 'emacs_keep_comments'
            comment: 'some reason this package was pinned.'
            package: 'emacs'
            pin: 'release n=unstable'
            pin_priority: 1001
            state: 'present'
          - name: 'non_existent_pin'
            state: 'absent'
          - name: 'yarn_remove'
            package: 'yarn'
            pin: 'origin deb.nodesource.com'
            pin_priority: 1001
            state: 'present'
platforms:
  - name: 'apt-debian-13-pin'
    image: 'ghcr.io/hifis-net/debian-systemd:13'
    systemd: 'always'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    pre_build_image: true
verifier:
  name: 'ansible'
lint: |
  set -e
  yamllint .
  ansible-lint .
scenario:
  test_sequence:
    # - 'dependency'
    # - 'cleanup'
    - 'destroy'
    - 'syntax'
    - 'create'
    # - 'prepare'
    - 'converge'
    # - 'idempotence'  # apt pin add/remove
    # - 'side_effect'
    - 'verify'
    # - 'cleanup'
    - 'destroy'
