---
- name: 'Converge | disabled'
  hosts: 'apt-debian-12-dist_upgrade_disable'
  gather_facts: false
  tasks:
    - name: 'Converge | apply r_pufky.deb.apt'
      ansible.builtin.include_role:
        name: 'r_pufky.deb.apt'
    - name: 'Converge | apply r_pufky.deb.apt'
      ansible.builtin.include_role:
        name: 'r_pufky.deb.apt'
      vars:
        apt_dist_upgrade_enable: true
