---
- name: 'Converge'
  hosts: 'apt-dist-upgrade-disable'
  gather_facts: false
  tasks:
    - name: 'Converge | role | r_pufky.deb.apt'
      ansible.builtin.include_role:
        name: 'r_pufky.deb.apt'

    - name: 'Converge | role | r_pufky.deb.apt (dist upgrade)'
      ansible.builtin.include_role:
        name: 'r_pufky.deb.apt'
      vars:
        apt_srv_dist_upgrade_always: true
