---
- name: 'Verify | disable'
  hosts: 'apt-debian-13-dist_upgrade_disable'
  gather_facts: false
  tasks:
    - name: 'Verify | disable | APT history.log'
      ansible.builtin.shell: >-
        set -o pipefail |
        grep -ri dist-upgrade /var/log/apt/history.log |
        wc -l
      changed_when: false
      args:
        executable: '/bin/bash'
      register: _test_apt_dist_disable

    - name: 'Verify | disable | assert no dist-upgrades'
      ansible.builtin.assert:
        quiet: true
        that:
          - _test_apt_dist_disable.stdout == '0'
        fail_msg: >
          ✘ dist-upgrade should not be run.
          (run {{ _test_apt_dist_disable.stdout }}).

- name: 'Verify | standard'
  hosts: 'apt-debian-13-dist_upgrade'
  gather_facts: false
  tasks:
    - name: >
        Converge | standard |
        apply r_pufky.deb.apt (dist-upgrade run, sources changed)
      ansible.builtin.include_role:
        name: 'r_pufky.deb.apt'
    - name: >
        Converge | standard |
        apply r_pufky.deb.apt (dist-upgrade NOT run, sources same)
      ansible.builtin.include_role:
        name: 'r_pufky.deb.apt'
    - name: >
        Converge | standard |
        apply r_pufky.deb.apt (dist-upgrade run, sources same, upgrade enabled)
      ansible.builtin.include_role:
        name: 'r_pufky.deb.apt'
      vars:
        apt_dist_upgrade_enable: true

    - name: 'Verify | standard | MANUAL VERIFICATION ⚠'
      ansible.builtin.debug:
        msg: |
          ╭───────────────────────────────────────────────────────────────────╮
          │                                                                   │
          │                       MANUAL VERIFICATION.                        │
          │                                                                   │
          ├───────────────────────────────────────────────────────────────────╯
          │ Confirm:
          │ * dist-upgrade run: source changed
          │ * dist-upgrade not run: no source change
          │ * dist-upgrade run: no source change,apt_dist_upgrade_enable=true

- name: 'Verify | enable'
  hosts: 'apt-debian-13-dist_upgrade_enable'
  gather_facts: false
  tasks:
    - name: >
        Converge | enable |
        apply r_pufky.deb.apt (dist-upgrade run, sources changed)
      ansible.builtin.include_role:
        name: 'r_pufky.deb.apt'
    - name: >
        Converge | enable |
        apply r_pufky.deb.apt (dist-upgrade NOT run, sources same)
      ansible.builtin.include_role:
        name: 'r_pufky.deb.apt'

    - name: 'Verify | standard | MANUAL VERIFICATION ⚠'
      ansible.builtin.debug:
        msg: |
          ╭───────────────────────────────────────────────────────────────────╮
          │                       MANUAL VERIFICATION.                        │
          │                                                                   │
          │                                                                   │
          ├───────────────────────────────────────────────────────────────────╯
          │ Confirm:
          │ * dist-upgrade run: source changed
          │ * dist-upgrade not run: no source change
