---
- name: 'Verify'
  hosts: 'apt-dist-upgrade-disable'
  gather_facts: false
  tasks:
    - name: 'Verify | cmd | query /var/log/apt/history.log'
      ansible.builtin.shell: >-
        set -o pipefail |
        grep -ri dist-upgrade /var/log/apt/history.log |
        wc -l
      changed_when: false
      args:
        executable: '/bin/bash'
      register: test__apt_dist_disable

    - name: 'Verify | assert | no dist-upgrades'
      ansible.builtin.assert:
        quiet: true
        that:
          - test__apt_dist_disable.stdout == '0'
        fail_msg: |

          ✘ dist-upgrade should not be run.

          run {{ test__apt_dist_disable.stdout }}

- name: 'Verify'
  hosts: 'apt-dist-upgrade'
  gather_facts: false
  tasks:
    - name:
        'Verify | role | r_pufky.deb.apt (dist-upgrade run, sources changed)'
      ansible.builtin.include_role:
        name: 'r_pufky.deb.apt'

    - name:
        'Verify | role | r_pufky.deb.apt (dist-upgrade NOT run, sources same)'
      ansible.builtin.include_role:
        name: 'r_pufky.deb.apt'

    - name: '{{
          "Verify | role | r_pufky.deb.apt " ~
          "(dist-upgrade run, sources same, upgrade enabled)"
        }}'
      ansible.builtin.include_role:
        name: 'r_pufky.deb.apt'
      vars:
        apt_srv_dist_upgrade_always: true

    # yamllint disable rule:line-length
    - name: 'Verify | 🛆 MANUAL VERIFICATION REQUIRED 🛆'
      ansible.builtin.debug:
        msg: |

          🛆 MANUAL VERIFICATION REQUIRED 🛆

          Confirm role application steps (apt-dist-upgrade):
          * dist-upgrade run ➔ source changed
          * dist-upgrade not run ➔ no source change
          * dist-upgrade run ➔ no source change, apt_srv_dist_upgrade_always=true

- name: 'Verify'
  hosts: 'apt-dist-upgrade-enable'
  gather_facts: false
  tasks:
    - name:
        'Verify | role | r_pufky.deb.apt (dist-upgrade run, sources changed)'
      ansible.builtin.include_role:
        name: 'r_pufky.deb.apt'

    - name:
        'Verify | role | r_pufky.deb.apt (dist-upgrade NOT run, sources same)'
      ansible.builtin.include_role:
        name: 'r_pufky.deb.apt'

    - name: 'Verify | 🛆 MANUAL VERIFICATION REQUIRED 🛆'
      ansible.builtin.debug:
        msg: |

          🛆 MANUAL VERIFICATION REQUIRED 🛆

          Confirm role application steps (apt-dist-upgrade-enable):
          * dist-upgrade run ➔ source changed
          * dist-upgrade not run ➔ no source change
