---
###############################################################################
# Apt Source List
###############################################################################
# Reference:
# * https://wiki.debian.org/SourcesList

- name: 'Sources | filesystem | disable /etc/apt/sources.list'
  when: apt_srv_sources_list_disable and not apt_srv_sources_list_modernize
  ansible.builtin.replace:
    path: '/etc/apt/sources.list'
    regexp: '^(?!\s*#)(.*)$'
    replace: '# \1'
  failed_when: false  # sources.list may already be removed.

- name: 'Sources | apt | modernize sources'
  when: apt_srv_sources_list_modernize
  ansible.builtin.command: 'apt modernize-sources --assume-yes'
  register: apt__modernize
  changed_when: "'Modernizing' in apt__modernize.stdout"

- name: 'Sources | filesystem | modify sources'
  when: apt_sources | length > 0
  block:
    - name: '{{ "Sources | filesystem | set deb822" }}'
      ansible.builtin.deb822_repository:
        allow_downgrade_to_insecure:
          '{{ item.allow_downgrade_to_insecure | default(omit) }}'
        allow_insecure: '{{ item.allow_insecure | default(omit) }}'
        allow_weak: '{{ item.allow_weak | default(omit) }}'
        architectures: '{{ item.architectures | default(omit) }}'
        by_hash: '{{ item.by_hash | default(omit) }}'
        check_valid_until: '{{ item.check_valid_until | default(omit) }}'
        components: '{{ item.components | default(omit) }}'
        date_max_future: '{{ item.date_max_future | default(omit) }}'
        enabled: '{{ item.enabled | default(omit) }}'
        inrelease_path: '{{ item.inrelease_path | default(omit) }}'
        install_python_debian:
          '{{ item.install_python_debian | default(false) }}'
        languages: '{{ item.languages | default(omit) }}'
        mode: '{{ item.mode | default("0644") }}'
        name: '{{ item.name }}'
        pdiffs: '{{ item.pdiffs | default(omit) }}'
        signed_by: '{{ item.signed_by }}'
        state: '{{ item.state | default("present") }}'
        suites: '{{ item.suites | default(omit) }}'
        targets: '{{ item.targets | default(omit) }}'
        trusted: '{{ item.trusted | default(omit) }}'
        types: '{{ item.types | default(["deb"]) }}'
        uris: '{{ item.uris }}'
      loop: '{{ apt_sources }}'
      loop_control:
        label: '{{ item.name }}'
      register: apt__sources

    - name: 'Sources | apt | update cache'  # noqa no-handler immediate.
      when: apt__sources.changed
      ansible.builtin.apt:
        update_cache: true

- name: 'Sources | distribution'
  when: >
    not apt_srv_dist_upgrade_disable and
    (apt_srv_dist_upgrade_always or (apt__sources.changed | default(false)))
  block:
    - name: 'Sources | distribution | query /boot'
      when: apt_srv_auto_grub_boot
      ansible.builtin.command: 'grub-probe --target=disk /boot'
      changed_when: false
      failed_when: false  # Containers will not have command.
      register: apt__grub_boot

    - name: 'Sources | distribution | set grub-pc /boot'
      when: apt_srv_auto_grub_boot and apt__grub_boot.rc == 0
      ansible.builtin.debconf:
        name: 'grub-pc'
        question: 'grub-pc/install_devices'
        value: '{{ apt__grub_boot.stdout_lines | first | trim }}'
        vtype: 'multiselect'

    - name: 'Sources | distribution | 🗘 upgrade in progress (~2 minutes) 🗘'
      ansible.builtin.debug:
        msg: 'Distribution is being upgraded (~2 minutes).'

    - name: 'Sources | distribution | upgrade packages'
      ansible.builtin.apt:
        upgrade: 'dist'
        state: '{{ apt_srv_package_state | default(apt___app._state) }}'
        update_cache: true
      async: '{{ apt_srv_timeout | default(apt___app._timeout) }}'
      poll: '{{ apt_srv_poll | default(apt___app._poll) }}'
