---
###############################################################################
# Debian Role Options
###############################################################################

# Last time debian options were validated against a default configuration.
apt_role_validate_date: '2025-08-21'
apt_role_validate_release: 'trixie`'

# Default state for apt package installation. See ansible.builtin.apt.
apt_role_package_state: 'present'

# Default timeout for long actions (seconds).
apt_role_timeout: 600

# Default number of polls (count).
apt_role_poll: 5

###############################################################################
# APT Packages
###############################################################################

apt_role_packages:
  - 'python3-debian'  # DEB822.
  - 'ca-certificates'  # CA certificates for apt source validation.

apt_role_unattended_packages:
  - 'apt-listchanges'  # Installed by default.
  - 'unattended-upgrades'  # Installed by default.
  - 'apt-config-auto-update'  # Config automation support.

apt_role_ac_power_packages:
  - 'powermgmt-base'  # Power management detection.
