---
- name: 'Prepare'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Prepare | add packages to be removed'
      ansible.builtin.apt:
        name:
          - 'git'
          - 'curl'
          - 'git-lfs'
        state: 'present'
