---
# Ensure list of lists for apt packages work without causing failures. All
# package specifications should be flatten and executed without error.

- name: 'List of lists | verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'List of lists | verify | gather installed packages'
      ansible.builtin.package_facts:

    - name: 'List of lists | verify | assert packages installed and removed'
      ansible.builtin.assert:
        that:
          - '"vim" in ansible_facts.packages'
          - '"htop" in ansible_facts.packages'
          - '"tmux" in ansible_facts.packages'
          - '"git" not in ansible_facts.packages'
          - '"curl" not in ansible_facts.packages'
          - '"git-lfs" not in ansible_facts.packages'
        fail_msg: >
          should be installed: vim, htop, tmux.
          should be removed: git, curl, git-lfs.
