---
- name: 'Verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Verify | fact | query installed packages'
      ansible.builtin.package_facts:

    - name: 'Verify | assert | package install/remove state correct'
      ansible.builtin.assert:
        quiet: true
        that:
          - '"vim" in ansible_facts.packages'
          - '"htop" in ansible_facts.packages'
          - '"tmux" in ansible_facts.packages'
          - '"git" not in ansible_facts.packages'
          - '"curl" not in ansible_facts.packages'
          - '"git-lfs" not in ansible_facts.packages'
        fail_msg: |

          ✘ Package state not correct.

          Should be installed:
          * vim
          * htop
          * tmux

          Should be removed:
          * git
          * curl
          * git-lfs
