---
###############################################################################
# Service
###############################################################################

# Always run dist-upgrade?
#
# Special Case:
#   * apt_srv_dist_upgrade_disable has precedence. If both are true,
#     dist-upgrade will be disabled.
#
# Values:
#    True: Always dist-upgrade run during role execution.
#   False: Trigger dist-upgrade run if APT sources are changed (default).
#
# Default: False.
apt_srv_dist_upgrade_always: false

# Disable dist-upgrade?
#
# Special Case:
#   * Precedence over apt_srv_dist_upgrade_always. If both are true,
#     dist-upgrade will be disabled.
#
# Values:
#    True: Never dist-upgrade run during role execution.
#   False: Trigger dist-upgrade run if APT sources are changed (default).
#
# Default: False.
apt_srv_dist_upgrade_disable: false

# Automatically determine GRUB boot disk?
#
# In cases where dist-upgrade also upgrades grub-pc, a disk must be specified
# or the upgrade will require interactive resolution. Enabling uses grub-probe
# to determine disk associated with /boot use that during upgrade.
#
# Complex systems may require manual resolution and may result in broken
# systems. In most cases this should be disabled. This has no effect on
# containers.
#
# Default: False.
apt_srv_auto_grub_boot: false

# Disable /etc/apt/sources.list?
#
# Mutually exclusive with apt_srv_sources_list_modernize.
#
# Disabled via commenting all lines in /etc/apt/sources.list.
#
# Upgraded installs, or ones using stand-alone .deb packages may still use
# sources.list and may cause APT sourcing conflicts.
#
# Default: False.
apt_srv_sources_list_disable: false

# Modernize sources.list?
#
# Mutually exclusive with apt_srv_sources_list_disable.
#
# Use modernize-sources tool to migrate sources.list to sources.list.d in
# DEB822 format, creating a backup in sources.list.bak. Highly recommend
# explicitly defining APT sources manually.
#
# Default: False.
apt_srv_sources_list_modernize: false

# Timeout for dist-upgrade to complete (seconds). Default: 600.
apt_srv_timeout: 600

# Number of polling attempts between apt_srv_timeout (count). Default: 5.
apt_srv_poll: 5

# Ansible APT Defaults
###############################################################################
# Defaults used when calling ansible.builtin.apt within the role.

# Ansible APT package state.
#
# Values:
#      absent: Remove apt_packages.
#   build-dep: Install build dependencies with apt_packages.
#      latest: Install latest apt_packages version.
#     present: Ensure apt_packages are installed.
#       fixed: Attempt to fix installed apt_packages.
#
# Default: 'present'.
apt_srv_package_state: 'present'

# Autoremove unused dependencies (except build-dep). Default: True.
apt_srv_package_autoremove: true

# Purge package configuration files on remove? Default: True.
apt_srv_package_purge: true

# Install recommended packages in addition to apt_packages?
#
# Suggested packages are never installed.
#
# Default: True.
apt_srv_package_install_recommends: true

# Update APT cache before package operation?
#
# dist-upgrades will **always** update cache.
#
# Default: False.
apt_srv_package_update_cache: false
