---
###############################################################################
# APT Sources
###############################################################################
# Use DEB822 format.
#
# apt_sources:
#     list of dict - ansible.builtin.deb822_repository.
#   - allow_downgrade_to_insecure: bool - Allow downgrading a package that was
#           previously authenticated but is no longer authenticated?
#         Default: omit (system default).
#     allow_insecure: bool - Allow insecure repositories>?
#         Default: omit (system default).
#     allow_weak: bool - Allow repo signed with a key using a weak algorithm?
#         Default: omit (system default).
#     architectures: list of str - Architectures to search within repository?
#         Default: omit (system default).
#     by_hash: bool - Acquire indexes via a URI constructed from a hashsum of
#           the expected file instead of using the well-known stable filename?
#         Default: omit (system default).
#     check_date: bool - Should APT consider the machine time correct?
#         Default: omit (system default).
#     check_valid_until: bool - Should APT try to detect replay attacks?
#         Default: omit (system default).
#     components: list of str - Components specify different sections of one
#           distribution version present in a Suite.
#         Default: omit (system default).
#     date_max_future: int - How far (days) in the future a repo may be
#         Default: omit (system default).
#     enabled: bool - Enable source?
#         Default: omit (system default).
#     inrelease_path: str - Path to the InRelease file, relative to the normal
#           position of an InRelease file.
#         Default: omit (system default).
#     install_python_debian: bool - Automatically try to install Python debian
#           library? Without this library, the module does not work. Runs
#           'apt install python3-debian'. Only works with system Python. If you
#           are using Python on remote that is not system Python, set
#           install_python_debian=false and ensure that Python debian library
#           for your Python version is installed some other way.
#         Default: Fa lse (system default).
#     languages: list of str - Which language information should be downloaded
#         Default: omit (system default).
#     mode: str - Octal sources file permission
#         Default: '0644'
#     name: str - Name of the repo (used for X-Repolib-Name, repo, signing key)
#     pdiffs: bool - Use partial diffs to update old indexes?
#         Default: omit (system default).
#     signed_by: str - URI, GPG key, ASCII armored GPG public block, absolute
#             keyring file path, or key fingerprints to verify repository.
#     state: str - state
#         Default: 'present'.
#     suites: list of str - Specify an exact path in relation to the URI(s)
#           provided, in which case the Components: must be omitted and suite
#           must end with a slash (/). Alternatively, it may take the form of a
#           distribution version (e.g. a version codename like disco or
#           artful). If the suite does not specify a path, at least one
#           component must be present.
#         Default: omit (system default).
#     targets: list of str - Download targets apt will try to acquire
#         Default: omit (system default).
#     trusted: bool - Consider trusted or raise warnings when installed?
#         Default: omit (system default).
#     types: list of str - Types of packages from source (deb, deb-src)
#         Default: ['deb'].
#     uris: list of str - Base Debian distribution archive
#
# Default:
#  - name: 'debian'
#    types:
#      - 'deb'
#      - 'deb-src'
#    uris: 'http://deb.debian.org/debian'
#    suites:
#      - 'trixie'
#      - 'trixie-updates'
#      - 'trixie-backports'
#    components:
#      - 'main'
#      - 'contrib'
#      - 'non-free'
#      - 'non-free-firmware'
#    signed_by: '/usr/share/keyrings/debian-archive-keyring.gpg'
#  - name: 'debian-security'
#    types:
#      - 'deb'
#      - 'deb-src'
#    uris: 'http://deb.debian.org/debian-security'
#    suites:
#      - 'trixie-security'
#    components:
#      - 'main'
#      - 'contrib'
#      - 'non-free'
#      - 'non-free-firmware'
#    signed_by: '/usr/share/keyrings/debian-archive-keyring.gpg'
#
# Reference:
# * https://wiki.debian.org/SourcesList
# * https://repolib.readthedocs.io/en/latest/deb822-format.html
# * https://manpages.debian.org/unstable/apt/sources.list.5.en.html
apt_sources:
  - name: 'debian'
    types:
      - 'deb'
      - 'deb-src'
    uris: 'http://deb.debian.org/debian'
    suites:
      - 'trixie'
      - 'trixie-updates'
      - 'trixie-backports'
    components:
      - 'main'
      - 'contrib'
      - 'non-free'
      - 'non-free-firmware'
    signed_by: '/usr/share/keyrings/debian-archive-keyring.gpg'
  - name: 'debian-security'
    types:
      - 'deb'
      - 'deb-src'
    uris: 'http://deb.debian.org/debian-security'
    suites:
      - 'trixie-security'
    components:
      - 'main'
      - 'contrib'
      - 'non-free'
      - 'non-free-firmware'
    signed_by: '/usr/share/keyrings/debian-archive-keyring.gpg'
