---
- name: 'Prepare'
  hosts: 'apt-default-unattended'
  gather_facts: false
  tasks:
    - name: 'Prepare | inject | /etc/apt/sources.list'
      ansible.builtin.copy:
        src: 'files/sources.list'
        dest: '/etc/apt/sources.list'
        owner: 'root'
        group: 'root'
        mode: '0644'
