---
- name: 'Default | verify | sources'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Default | verify | sources'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: 'Default | verify | sources | {{ item }}'
        test_file: '{{ item }}'
        test_owner: 'root'
        test_group: 'root'
        test_mode: '0644'
        test_state: 'file'
      loop:
        - '/etc/apt/sources.list.d/debian.sources'
        - '/etc/apt/sources.list.d/debian-security.sources'

- name: 'Default | verify | unattended'
  hosts: 'apt-debian-12-default-unattended'
  gather_facts: false
  tasks:
    - name: 'Default | verify | unattended'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: 'Default | verify | unattended | {{ item }}'
        test_file: '{{ item }}'
        test_owner: 'root'
        test_group: 'root'
        test_mode: '0644'
        test_state: 'file'
      loop:
        - '/etc/apt/apt.conf.d/20auto-upgrades'
        - '/etc/apt/apt.conf.d/50unattended-upgrades'

    - name: 'Default | verify | unattended | gather installed packages'
      ansible.builtin.package_facts:

    - name: 'Default | verify | unattended | gather service status'
      ansible.builtin.service_facts:

    - name: 'Default | verify | unattended | assert packages installed/removed'
      ansible.builtin.assert:
        quiet: true
        that:
          - '"apt-listchanges" in ansible_facts.packages'
          - '"unattended-upgrades" in ansible_facts.packages'
          - '"apt-config-auto-update" in ansible_facts.packages'
          - '"powermgmt-base" not in ansible_facts.packages'
        fail_msg: >
          ✘ apt-listchanges, unattended-upgrades, apt-config-auto-update
          should be installed. powermgmt-base should not be installed.

    - name: 'Default | verify | unattended | assert services active'
      ansible.builtin.assert:
        quiet: true
        that:
          - '"apt-daily.service" in ansible_facts.services'
          - '"apt-daily-upgrade.service" in ansible_facts.services'
          - '"unattended-upgrades.service" in ansible_facts.services'
        fail_msg: >
          ✘ apt-daily, apt-upgrade, unattended-upgrade services should be
          enabled.

    - name: 'Default | verify | unattended | execute dry run config check'
      ansible.builtin.command: 'unattended-upgrade --dry-run'
      register: _test_apt_unattended_upgrade_check
      changed_when: false
      failed_when: _test_apt_unattended_upgrade_check.rc != 0

- name: 'Default | verify | unattended | enabled'
  hosts: 'apt-debian-12-default-unattended'
  gather_facts: false
  tasks:
    - name: 'Default | verify | 52unattended-upgrades-local'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: 'Default | verify | 52unattended-upgrades-local'
        test_src: 'files/52unattended-upgrades-local'
        test_file: '/etc/apt/apt.conf.d/52unattended-upgrades-local'
        test_owner: 'root'
        test_group: 'root'
        test_mode: '0644'
